//{
//    "organization": {
//    "regionId": 1,
//    "districtId": 16,
//    "phoneNumber": "998996696",
//    "address": "CHILONZOR",
//    "residentOfUzb": 0,
//    "citizenshipId": 210,
//    "tb_inps": "12345678998765",
//    "tb_paspsery": "AB",
//    "tb_paspnumber": "6369999",
//    "tb_surname": "FAM1",
//    "tb_name": "NAM1",
//    "tb_patronym": "FATHERS NAME1",
//    "tb_datebirth": "01.12.1997",
//    "tb_paspvidan": "TOSH SHAXAR",
//    "tb_paspdate": "01.12.2015",
//    "tb_prava_sery": "ABD",
//    "tb_prava_number": "1234567",
//    "tb_prava_date": "01.12.2020",
//    "tb_pol": 0,
//    "MARKA": 1,
//    "MODEL": 1,
//    "TYPE": 1,
//    "YEAR": "01.12.2020",
//    "TEXPREO": 1,
//    "MOSCH": 1,
//    "OWNER_ISDRIVER": 0,
//    "VMODEL": "ACE ",
//    "REGNUMBER": "987AB",
//    "KUZOV": "120993994",
//    "SHASSI": "1234556",
//    "DVIGATEL": "9393938",
//    "TEXPSERY": "1234567",
//    "TEXPNUMBER": "1234567",
//    "INSURER_ACTIVITY": "INSURER_ACTIVITYi",
//    "TEXPDATE": "01.12.2020",
//    "phoneNumber2": "",
//    "fax": "",
//    "email": ""
//},
//    "details": {
//    "contractDate": "21.12.2020",
//    "paymentDate": "21.12.2020",
//    "issueDate": "21.12.2020",
//    "seria": "UIU",
//    "number": "7000003",
//    "agent_login": "test_agent",
//    "driver_limit": 5,
//    "date_from": "21.12.2020",
//    "date_to": "5.1.2021",
//    "HAS_BENEFIT": 1,
//    "CONTRACT_TERM": 3,
//    "CONTRACT_PERIOD": 1,
//    "IS_TAXI": 0,
//    "DRIVER_CNT": 5,
//    "USE_TERRITORY": 1,
//    "INVEST_PROJECT": 1,
//    "IS_SEZ": 6,
//
//    "D1_RELATIVE": "1.0",
//    "D1_EXPERIENCE": "5",
//    "D1_ACCYEAR": "",
//    "D1_ACCCNT": "",
//    "D1_PASPSERY": "AB",
//    "D1_PASPNUMBER": "6369999",
//
//    "D1_PASPVIDAN": "01.02.2003",
//
//    "D1_PINFL": "123",
//    "D1_SURNAME": "FAM3",
//    "D1_NAME": "NAM3",
//    "D1_PATRONYM": "FATHER NAME 3",
//    "D1_LICSERY": "ABB",
//    "D1_LICNUMBER": "6369999",
//    "D1_PASPDATE": "01.12.2015",
//    "D1_DATEBIRTH": "01.12.1997",
//    "D1_LICDATE": "13.03.2020",
//
//    "D2_RELATIVE": "0",
//    "D2_EXPERIENCE": "0",
//    "D2_ACCYEAR": "0",
//    "D2_ACCCNT": "0",
//    "D2_PASPSERY": "",
//    "D2_PASPNUMBER": "",
//    "D2_PASPVIDAN": "",
//    "D2_PINFL": "",
//    "D2_SURNAME": "",
//    "D2_NAME": "",
//    "D2_PATRONYM": "",
//    "D2_LICSERY": "",
//    "D2_LICNUMBER": "",
//    "D2_PASPDATE": "",
//    "D2_DATEBIRTH": "",
//    "D2_LICDATE": "",
//
//    "D3_RELATIVE": "0",
//    "D3_EXPERIENCE": "0",
//    "D3_ACCYEAR": "0",
//    "D3_ACCCNT": "0",
//    "D3_PASPSERY": "",
//    "D3_PASPNUMBER": "",
//    "D3_PASPVIDAN": "",
//    "D3_PINFL": "",
//    "D3_SURNAME": "",
//    "D3_NAME": "",
//    "D3_PATRONYM": "",
//    "D3_LICSERY": "",
//    "D3_LICNUMBER": "",
//    "D3_PASPDATE": "",
//    "D3_DATEBIRTH": "",
//    "D3_LICDATE": "",
//
//    "D4_RELATIVE": "0",
//    "D4_EXPERIENCE": "0",
//    "D4_ACCYEAR": "0",
//    "D4_ACCCNT": "0",
//    "D4_PASPSERY": "",
//    "D4_PASPNUMBER": "",
//    "D4_PASPVIDAN": "",
//    "D4_PINFL": "",
//    "D4_SURNAME": "",
//    "D4_NAME": "",
//    "D4_PATRONYM": "",
//    "D4_LICSERY": "",
//    "D4_LICNUMBER": "",
//    "D4_PASPDATE": "",
//    "D4_DATEBIRTH": "",
//    "D4_LICDATE": "",
//
//    "D5_RELATIVE": "0",
//    "D5_EXPERIENCE": "0",
//    "D5_ACCYEAR": "0",
//    "D5_ACCCNT": "0",
//    "D5_PASPSERY": "",
//    "D5_PASPNUMBER": "",
//    "D5_PASPVIDAN": "",
//    "D5_PINFL": "",
//    "D5_SURNAME": "",
//    "D5_NAME": "",
//    "D5_PATRONYM": "",
//    "D5_LICSERY": "",
//    "D5_LICNUMBER": "",
//    "D5_PASPDATE": "",
//    "D5_DATEBIRTH": "",
//    "D5_LICDATE": ""
//},
//    "cost": {
//    "insurancePremium": 33600,
//    "sumInsured": "40000000",
//    "insurancePremiumPaidToInsurer": 33600
//}
//}